branches:
  only:
    - master

os: linux
dist: xenial

language: python
python:
  - 3.8
  - 3.9-dev

install:
  - pip install -r test-requirements.txt

script:
  - pyflakes fourth tests setup.py
  - black --check --diff fourth tests setup.py
  - python -m unittest
