os: linux
dist: xenial

language: python
python:
  - 3.8
  - 3.9-dev

install:
  - pip install -r test-requirements.txt

script:
  - pyflakes fourth tests setup.py
  - black --check --diff fourth tests setup.py
  - python -m unittest

deploy:
  provider: pypi
  username: __token__
  password:
    secure: "xxhErRU7QLYAd1Nx2y3kgVyk46d5qMUSIlfj4r7ryDmboy7Wd8ODhIIq2hi2u4JmZqvSlN3boMf+VCypnovFRYy9L3mN5d8/rGKdHXZ8zaJ0XRcEUJsPF7MRGSVrAWvo5zAQegGaMitU0eyorHTjhlmR9cEIwvqQkLf5e94JRIcPHaTv8ouGZbne+GrRDxoTBc1eo5g5aWnwXQx37lK0ItBdWTG4HnUNLNuDkDtxT2gOuIdz1m7ezT0rZMTRXPgwqDMx5dk/8RdqbydYHszybfcx3UBvDvcwx1U2T3eptuIm0E6LelqTYhm5EPr3fG5piB8wkG6RWdHEan1yxO56j6hzVJFs+ol8b7IPqOzdQU5XuH2PAzxVto1FrEmpPI8Up3xlO8e748EeIUh9AmVr8lXuKUGA3z70Xjd+zu/q6Mgz23mimP6q3nRYTSfagWBPe/AV2Gr0bDJ5GMSI4gki93UryDVMh1mYTaatjLGeH4R7w14v4yB8/bWUbzIlNVitHN+ElawYSXoPqtbbo0YmkzuTq3Io+bK9jT4Z+TPUVVjBpcppVms7sxgK2Teryt8Q41vQ86pvem0L/p4LeTNSeDmT8YN3GcCrLHpscYx3eWBNoNY51ZBJKX7xdWkXNfr1YNzbxM7fO3qU7J+fFk1HhtsdJo3YNLqvn7w4dgEf1bc="
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
    repo: LincolnPuzey/Fourth
