os: linux
dist: xenial

language: python
python:
  - 3.7
  - 3.8
  - 3.9-dev

install:
  - pip install -r test-requirements.txt

script:
  - pyflakes fourth tests setup.py
  - black --check --diff fourth tests setup.py
  - isort . --check-only --diff
  - mypy fourth
  - coverage run -m unittest

after_success:
  - codecov --file .coverage/coverage.xml

deploy:
  provider: pypi
  username: __token__
  password:
    secure: U/dK8TjdXtYpyPjOT8LtJJqT3LZizEeiimIPhgI+AEBOiC9SOEVquMfAQXJhQSajoWymOWmD/A4rBeRMJzURs08vtRybjhGrj2UCRCOsUOfCXLIGk3KFtHpNCxkKimspOiyoKmBDJNnZWkyAGWiI+0TeBAhQmtfIfdMgiUe+jkZkUQsJTehXqJ9uagsIt/pmKG6w+9LVvuTCjlUIOR5PVIRXwL6EMgobyW5V/IlGmtNn2sgxkp2yIHQfNFW4+kVKSlSH/xJNG4BKFjwB1xzztd5UVifRSDkwNGgDos9UbTJEaZKZLrRYvzWmObjpfpa7DhF5863K7KGGA6uTwlYmiBOufBHcCm97vJwBwZiP9I51Nv22d6vDFEL8F9NuQ1QtbA7ZdqlYwGa1nnOTMlh0a06i1gz9+2h+nDPKNBlNvXJEm5MURMS/73m0pUXtMJ8E8U3RuO1VsHKfOuS0wVpbP7saCXBD9RBmVc61dyw2yqL6zIY8i1BlTsTzSDJhpNHv+ObX4I+r50lYahsSBD0UJOTMhcR8hURRk8t5jiHTaPaCHzNG+Mafk9+1ZWrO0NjaFbUFw9ei1tzu8KDZeAbD52vzV/24jAAzOJTsZf6p4ZtAA6zQEPObdROaPhgPSzE83GTd1dLLyT9r5xcjnj6XbMwPn5cbfsIQrS8h8+rV9Jg=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
    repo: LincolnPuzey/Fourth
  edge: true  # opt in to dpl v2
