[tool.black]
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = 'black'
add_imports = ['from __future__ import annotations']

[tool.coverage.run]
branch = true
source = ['fourth']
data_file = '.coverage/coverage.sqlite3'

[tool.coverage.html]
directory = '.coverage/htmlcov'

[tool.coverage.xml]
output = '.coverage/coverage.xml'

[tool.coverage.json]
output = '.coverage/coverage.json'
